auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: r4phael's Blog
url: http://albus12138.github.io
feed: /atom.xml
author_info: <a href="http://albus12138.github.io">R4phael</a>
