markdown: kramdown
highlighter: pygments
paginate: 7
paginate_path: "page_:num"
permalink: /:categories/:title

title: Raphael's Blog
url: http://albus12138.github.io
author_info: <a href="http://albus12138.github.io">Raphael</a>

plugins: [jekyll-paginate]