auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Albus's Blog
url: http://albus12138.github.io
feed: /atom.xml
author_info: <a href="http://albus12138.github.io">Albus</a>
